// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPgV1OITGbBoYEKcsTqC36k6RsW4qe5AI',
    appId: '1:391681982929:web:c683503ece6ca343f320f0',
    messagingSenderId: '391681982929',
    projectId: 'itifinalteam3',
    authDomain: 'itifinalteam3.firebaseapp.com',
    storageBucket: 'itifinalteam3.firebasestorage.app',
    measurementId: 'G-E7Q4HGSCD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBxXX_mSbjenj2Dn28P7j2tcefFK6MG3I',
    appId: '1:391681982929:android:19943bb62d2f919ff320f0',
    messagingSenderId: '391681982929',
    projectId: 'itifinalteam3',
    storageBucket: 'itifinalteam3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBLfa16DDNW8HXw8dCg4RWzVDnLO4-Wmc',
    appId: '1:391681982929:ios:7f4681232d906530f320f0',
    messagingSenderId: '391681982929',
    projectId: 'itifinalteam3',
    storageBucket: 'itifinalteam3.firebasestorage.app',
    iosBundleId: 'com.example.itiFinalTeam3',
  );
}
